import Head from "next/head";
import Image from "next/image";
import Link from "next/link";

export default function Home() {
  return (
    <div className="index-page">
      <Head>
        <title>Rest Countries API</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1 style={{ "font-weight": "500" }}>
          <Link href={"https://restcountries.com/"}>
            <a className="link">REST Countries API</a>
          </Link>{" "}
          app using{" "}
          <Link href={"https://nextjs.org/"}>
            <a className="link">Next{".js"}</a>
          </Link>
        </h1>
        <div>
          This is aproject for practicing the use of the Next.js hooks Use{" "}
          <span
            style={{ "font-style": "oblique", "background-color": "#ECEFF4" }}
          >
            getStaticProps
          </span>{" "}
          and{" "}
          <span
            style={{ "font-style": "oblique", "background-color": "#ECEFF4" }}
          >
            getStaticPaths
          </span>{" "}
          using a restfull api
          <div>
            <Link href="/countries">
              <a className="link">Check out the project</a>
            </Link>
          </div>
        </div>
        {/*<h2>Development</h2*/}
        <h3>Pages</h3>
        <ul className="pages-ul">
          <li>
            index {"("}
            <Link href={"/"}>
              <a className="link">{"/"}</a>
            </Link>
            {")"}{" "}
          </li>
          <li>
            Countries index {"("}
            <Link href={"/countries"}>
              <a className="link">{"/countries"}</a>
            </Link>
            {")"}
          </li>
          <li>
            Countries-individual pages {"("}
            <Link href={"#"}>
              <a className="link">{"(/countries/[country-code])"}</a>
            </Link>
            {")"}
          </li>
        </ul>
        <h4>API</h4>
        Rest countries
        <h3></h3>
      </main>

      <footer>Made with love by Alejandro Pérez</footer>
    </div>
  );
}
