import Head from "next/head";
import Image from "next/image";
import Link from "next/link";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>Countries API using nextjs</h1>
        <div>
          <Link href="/countries">
            <a className="link">Countries</a>
          </Link>
        </div>
      </main>

      <footer></footer>
    </div>
  );
}
